{% set version = "1.0.0" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-uptasticsearch
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/uptasticsearch_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/uptasticsearch/uptasticsearch_{{ version }}.tar.gz
  sha256: 4d936fbe3d2e1b2d7850b70b07928dade43c41b3357b3f217efcd9c3802e2762

build:
  number: 1
  noarch: generic

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]

  host:
    - r-base >=3.3.0
    - r-curl
    - r-data.table
    - r-futile.logger
    - r-jsonlite
    - r-purrr
    - r-stringr

  run:
    - r-base >=3.3.0
    - r-curl
    - r-data.table
    - r-futile.logger
    - r-jsonlite
    - r-purrr
    - r-stringr

test:
  commands:
    - $R -e "library('uptasticsearch')"           # [not win]
    - "\"%R%\" -e \"library('uptasticsearch')\""  # [win]

about:
  home: https://github.com/uptake/uptasticsearch
  license: BSD-3-Clause
  summary: '''Elasticsearch'' is an open-source, distributed, document-based datastore (<https://www.elastic.co/products/elasticsearch>). It provides an ''HTTP'' ''API'' for querying the database and extracting datasets, but that ''API'' was not designed for common data science workflows like pulling large batches of records
    and normalizing those documents into a data frame that can be used as a training dataset for statistical models. ''uptasticsearch'' provides an interface for ''Elasticsearch'' that is explicitly designed to make these data science workflows easy and fun.'

  license_family: BSD
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/BSD_3_clause'
    - LICENSE

extra:
  recipe-maintainers:
    - jameslamb
    - austin3dickey
    - conda-forge/r
